print("Welcome to the Band Name Generator!")
City = input("What's the name of the city you grew up?\n")
Pet = input("What's your pet's name?\n")
Band_Name = ("Your band name could be " + City + " " + Pet)
print(Band_Name)
